### ISSUE TITLE
abnormal termination  when `messenger` communication causes network timeout

### ISSUE THREAD

**Issue by ainoya** [walter-cd/walter#130]
I met this abnormal exit when using slack notification.
Sorry, I put failure log later.

**Comment by takahi-i** [comment]
:+1:

**Comment by ainoya** [comment]
There was also error when DNS lookup was failed:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4fc4e6]

goroutine 19 [running]:
github.com/recruit-tech/walter/messengers.(*Slack).Post(0xc20803e5c0, 0xc20820a140, 0x38, 0x0)
	/Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/messengers/slack.go:57 +0x736
github.com/recruit-tech/walter/pipelines.(*Resources).ReportStageResult(0xc20800b140, 0x7f8539eb3428, 0xc20807a600, 0x1)
	/Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/pipelines/pipeline.go:42 +0x1eb
github.com/recruit-tech/walter/engine.(*Engine).ExecuteStage(0xc20801e680, 0x7f8539eb3428, 0xc20807a600)
	/Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/engine/engine.go:95 +0x7ec
github.com/recruit-tech/walter/engine.func·001(0x7f8539eb3428, 0xc20807a600)
	/Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/engine/engine.go:134 +0x3e
created by github.com/recruit-tech/walter/engine.(*Engine).executeAllChildStages
	/Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/engine/engine.go:135 +0x28e

goroutine 1 [chan receive]:
github.com/recruit-tech/walter/engine.(*Engine).Execute(0xc20801e680, 0x7f8539eb3428, 0xc20807a000, 0x0, 0x803830, 0x5, 0x0, 0x0, 0x0)
	/Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/engine/engine.go:186 +0x2b7
github.com/recruit-tech/walter/engine.(*Engine).executePipeline(0xc20801e680, 0xc20800abd0, 0x81c1f0, 0x8, 0x0, 0x0, 0x0)
	/Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/engine/engine.go:58 +0x299
github.com/recruit-tech/walter/engine.(*Engine).RunOnce(0xc20801e680, 0x1d)
	/Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/engine/engine.go:48 +0x5d
github.com/recruit-tech/walter/walter.(*Walter).Run(0xc208033b70, 0xe)
	/Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/walter/walter.go:61 +0xfd
main.main()
	/Users/takahi-i/work/walter/main.go:55 +0x2d9

goroutine 5 [chan receive]:
github.com/ainoya/glog.(*loggingT).flushDaemon(0x9e77e0)
	/Users/takahi-i/work/walter/gopath/src/github.com/ainoya/glog/glog.go:821 +0x78
created by github.com/ainoya/glog.init·1
	/Users/takahi-i/work/walter/gopath/src/github.com/ainoya/glog/glog.go:409 +0x2aa

goroutine 17 [chan send]:
github.com/recruit-tech/walter/engine.(*Engine).ExecuteStage(0xc20801e680, 0x7f8539eb3428, 0xc20807a240)
	/Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/engine/engine.go:112 +0xfaf
github.com/recruit-tech/walter/engine.func·001(0x7f8539eb3428, 0xc20807a240)
	/Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/engine/engine.go:134 +0x3e
created by github.com/recruit-tech/walter/engine.(*Engine).executeAllChildStages
	/Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/engine/engine.go:135 +0x28e

goroutine 7 [chan receive]:
github.com/recruit-tech/walter/engine.(*Engine).waitAllChildStages(0xc20801e680, 0xc2082edfb0, 0xc208033d10)
	/Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/engine/engine.go:149 +0x1e0
github.com/recruit-tech/walter/engine.(*Engine).ExecuteStage(0xc20801e680, 0x7f8539eb3428, 0xc20807a000)
	/Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/engine/engine.go:103 +0xb87
created by github.com/recruit-tech/walter/engine.(*Engine).Execute
	/Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/engine/engine.go:183 +0x24c

goroutine 18 [chan send]:
github.com/recruit-tech/walter/engine.(*Engine).ExecuteStage(0xc20801e680, 0x7f8539eb3428, 0xc20807a3c0)
	/Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/engine/engine.go:112 +0xfaf
github.com/recruit-tech/walter/engine.func·001(0x7f8539eb3428, 0xc20807a3c0)
	/Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/engine/engine.go:134 +0x3e
created by github.com/recruit-tech/walter/engine.(*Engine).executeAllChildStages
	/Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/engine/engine.go:135 +0x28e

goroutine 13 [sleep]:
net.func·019()
	/usr/local/Cellar/go/1.4.2/libexec/src/net/dnsclient_unix.go:240 +0x5a
created by net.loadConfig
	/usr/local/Cellar/go/1.4.2/libexec/src/net/dnsclient_unix.go:269 +0x20c
```

**Comment by mizzy** [comment]
I close this for cleaning issues. When this also occurs with v2 beta, please open a new issue.
