### ISSUE TITLE
Walter fails adding too much output to the buffering variables

### ISSUE THREAD

**Issue by takahi-i** [walter-cd/walter#152]
Walter failed with the following messages.

```
23:35:49  WARN [command] exec err: fork/exec /bin/sh: argument list too long
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5310d1]
goroutine 29 [running]:
github.com/recruit-tech/walter/stages.(*CommandStage).runCommand(0xc8200a8b40, 0x1)
    /Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/stages/command_stage.go:77 +0x441
github.com/recruit-tech/walter/stages.(*CommandStage).Run(0xc8200a8b40, 0x7f0173929ac8)
    /Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/stages/command_stage.go:51 +0x136
github.com/recruit-tech/walter/engine.(*Engine).executeStage(0xc820132480, 0x7f0173929ac8, 0xc8200a8b40, 0xc8204bd700, 0x1, 0x1, 0x0, 0x0)
    /Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/engine/engine.go:118 +0x460
github.com/recruit-tech/walter/engine.(*Engine).ExecuteStage(0xc820132480, 0x7f0173929ac8, 0xc8200a8b40)
    /Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/engine/engine.go:96 +0x535
created by github.com/recruit-tech/walter/engine.(*Engine).Execute
    /Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/engine/engine.go:202 +0x1e9
goroutine 1 [chan receive]:
github.com/recruit-tech/walter/engine.(*Engine).waitCloseOutputCh(0xc820132480, 0x7f0173929ac8, 0xc8200a8b40)
    /Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/engine/engine.go:209 +0x83
github.com/recruit-tech/walter/engine.(*Engine).Execute(0xc820132480, 0x7f0173929ac8, 0xc8200a8b40, 0xc82048ab70, 0x87c588, 0x5, 0x0, 0x0, 0x0)
    /Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/engine/engine.go:203 +0x214
github.com/recruit-tech/walter/engine.(*Engine).executePipeline(0xc820132480, 0xc82000ba10, 0x889f40, 0x8, 0x0, 0x0, 0x0)
    /Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/engine/engine.go:66 +0x2d5
github.com/recruit-tech/walter/engine.(*Engine).RunOnce(0xc820132480, 0x1d)
    /Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/engine/engine.go:56 +0x65
github.com/recruit-tech/walter/walter.(*Walter).Run(0xc820131170, 0xe)
    /Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/walter/walter.go:76 +0x102
main.main()
    /Users/takahi-i/work/walter/main.go:60 +0x2d9
goroutine 5 [chan receive, 2 minutes]:
github.com/ainoya/glog.(*loggingT).flushDaemon(0xa8e180)
    /Users/takahi-i/work/walter/gopath/src/github.com/ainoya/glog/glog.go:821 +0x67
created by github.com/ainoya/glog.init.1
    /Users/takahi-i/work/walter/gopath/src/github.com/ainoya/glog/glog.go:409 +0x29a
goroutine 20 [chan send]:
github.com/recruit-tech/walter/engine.(*Engine).finalizeMonitorChAfterExecute(0xc820132480, 0xc8204c1cc0, 0x1, 0x1, 0xc8204b7920, 0x0, 0x0)
    /Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/engine/engine.go:178 +0x159
github.com/recruit-tech/walter/engine.(*Engine).ExecuteStage(0xc820132480, 0x7f0173929ac8, 0xc8200a8480)
    /Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/engine/engine.go:104 +0x96e
github.com/recruit-tech/walter/engine.(*Engine).executeAllChildStages.func1(0xc820132480, 0xc82009a028)
    /Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/engine/engine.go:146 +0x81
created by github.com/recruit-tech/walter/engine.(*Engine).executeAllChildStages
    /Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/engine/engine.go:147 +0x27d
goroutine 16 [IO wait]:
net.runtime_pollWait(0x7f017392b100, 0x72, 0xc820014160)
    /usr/local/Cellar/go/1.5.1/libexec/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8201b2370, 0x72, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.1/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201b2370, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.1/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8201b2310, 0xc820405800, 0x800, 0x800, 0x0, 0x7f0173925050, 0xc820014160)
    /usr/local/Cellar/go/1.5.1/libexec/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82002a240, 0xc820405800, 0x800, 0x800, 0x0, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.1/libexec/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc82048a870, 0x7f017392b3b0, 0xc82002a240, 0x5, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.1/libexec/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc820260000, 0x939117, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.1/libexec/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc820260000, 0xc82001d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.1/libexec/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0x7f01738ed9a8, 0xc820260000, 0xc8204a65d8, 0xc82001d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.1/libexec/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc8204c14e0, 0xc82001d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc82032a960)
    /usr/local/Cellar/go/1.5.1/libexec/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc82032a960, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.1/libexec/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8204a6580)
    /usr/local/Cellar/go/1.5.1/libexec/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
    /usr/local/Cellar/go/1.5.1/libexec/src/net/http/transport.go:685 +0xc78
goroutine 21 [chan send]:
github.com/recruit-tech/walter/engine.(*Engine).finalizeMonitorChAfterExecute(0xc820132480, 0xc8204c1da0, 0x1, 0x1, 0xc8201996b0, 0x0, 0x0)
    /Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/engine/engine.go:178 +0x159
github.com/recruit-tech/walter/engine.(*Engine).ExecuteStage(0xc820132480, 0x7f0173929ac8, 0xc8200a86c0)
    /Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/engine/engine.go:104 +0x96e
github.com/recruit-tech/walter/engine.(*Engine).executeAllChildStages.func1(0xc820132480, 0xc82009a028)
    /Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/engine/engine.go:146 +0x81
created by github.com/recruit-tech/walter/engine.(*Engine).executeAllChildStages
    /Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/engine/engine.go:147 +0x27d
goroutine 22 [chan send]:
github.com/recruit-tech/walter/engine.(*Engine).finalizeMonitorChAfterExecute(0xc820132480, 0xc8204c1e60, 0x1, 0x1, 0xc8204b7980, 0x0, 0x0)
    /Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/engine/engine.go:178 +0x159
github.com/recruit-tech/walter/engine.(*Engine).ExecuteStage(0xc820132480, 0x7f0173929ac8, 0xc8200a8900)
    /Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/engine/engine.go:104 +0x96e
github.com/recruit-tech/walter/engine.(*Engine).executeAllChildStages.func1(0xc820132480, 0xc82009a028)
    /Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/engine/engine.go:146 +0x81
created by github.com/recruit-tech/walter/engine.(*Engine).executeAllChildStages
    /Users/takahi-i/work/walter/gopath/src/github.com/recruit-tech/walter/engine/engine.go:147 +0x27d
goroutine 33 [select]:
net/http.(*persistConn).writeLoop(0xc8204a6580)
    /usr/local/Cellar/go/1.5.1/libexec/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
    /usr/local/Cellar/go/1.5.1/libexec/src/net/http/transport.go:686 +0xc9d
Build step 'Execute shell' marked build as failure
```

**Comment by mizzy** [comment]
I close this for cleaning issues. When this problem also occurs with v2 beta, please open a new issue.
